apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: kishna/flask-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: PGDB_HOST
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: PGDB_HOST
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: REDIS_HOST
        - name: PGDB_USER
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: PGDB_USER
        - name: PGDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: PGDB_PASSWORD
        - name: PGDB_NAME
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: PGDB_NAME

