# flask-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
type: Opaque
data:
  PGDB_USER: cG9zdGdyZXM=           # base64 for 'postgres'
  PGDB_PASSWORD: cGxheWdyb3VuZA==   # base64 for 'playground'
  PGDB_NAME: bXlkYg==               # base64 for 'mydb'
