apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        envFrom:
         - secretRef:
            name: postgres-secret
